import Head from 'next/head'
import About_us from '../components/About_us'
import Banner from '../components/Banner'
import Cards from '../components/Cards'
import Counts from '../components/Counts'
import Header from '../components/Header'
import GreenCart from '../components/GreenCart'
import { BackspaceIcon, DatabaseIcon, HomeIcon, MinusSmIcon, MusicNoteIcon, NewspaperIcon, PhotographIcon, ViewGridIcon } from '@heroicons/react/outline'
import SmallCart from '../components/SmallCart'
import CardCursor from '../components/CardCursor'
import TitleComp from '../components/TitleComp'
import TrainCart from '../components/TrainCart'
import trainer  from "../public/assets/trainers/trainer-1.jpg"
import trainer2  from "../public/assets/trainers/trainer-2.jpg"
import trainer3  from "../public/assets/trainers/trainer-3.jpg"
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="scroll-smooth">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <Banner />
      <main>
        <section className="max-w-5xl mx-auto">
          <About_us />
        </section>
        <section className="bg-gray-100">
          <div className="max-w-5xl mx-auto grid grid-cols-2 md:grid-cols-4">
            <Counts 
              number= {1232}
              title= "Students"
            />
            <Counts 
              number= {64}
              title= "Courses"
            />
            <Counts 
              number= {42}
              title= "Events"
            />
            <Counts 
              number= {15}
              title= "Trainer"
            />
          </div>
        </section>
        <section className="max-w-5xl lg:max-w-6xl mx-auto">
          <div className="my-8 md:mx-10 md:grid md:grid-cols-1">
            <div className="md:grid grid-cols-1">
              <GreenCart />
            </div>
            <div className="md:grid md:grid-cols-2 lg:grid-cols-3">
              <Cards 
                NewspaperIcon={<NewspaperIcon className="h-14 bg-green-300 p-4 rounded-full" />}
                head="Ullamco laboris ladore pan"
                mean="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt"
              />
              <Cards 
                NewspaperIcon={<ViewGridIcon className="h-14 bg-green-300 p-4 rounded-full" />}
                head="Ullamco laboris ladore pan"
                mean="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt"
              />
              <Cards 
                NewspaperIcon={<PhotographIcon className="h-14 bg-green-300 p-4 rounded-full" />}
                head="Ullamco laboris ladore pan"
                mean="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt"
              />
            </div>
          </div>
        </section>
        <section className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4">
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={HomeIcon}
              color="text-blue-100"
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={MinusSmIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={MusicNoteIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart 
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
            <SmallCart
              _title="Lorem Ipsum"
              Icon={DatabaseIcon}
            />
          </div>
        </section>
        <section className="max-w-5xl mx-auto">
          <div className="mx-6 lg:mx-0">
            <TitleComp 
              compName="TRAINERS"
              compTitle="OUR PROFESSIONAL TRAINERS"
            />
          </div>
        </section>
        <section className="max-w-5xl mx-auto ">
          <div className="mx-8 grid grid-cols-1 md:grid-cols-2 gap-6 lg:grid-cols-3">
            <TrainCart 
              _img={trainer}
              c_name="Walter White"
              c_job="Web Development"
              c_desc="Magni qui quod omnis unde et eos fuga et exercitationem. Odio veritatis perspiciatis quaerat qui aut aut aut"
            />
            <TrainCart 
              _img={trainer2}
              c_name="Sarah Jhinson"
              c_job="Marketing"
              c_desc="Magni qui quod omnis unde et eos fuga et exercitationem. Odio veritatis perspiciatis quaerat qui aut aut aut"
            />
            <TrainCart 
              _img={trainer3}
              c_name="William Anderson"
              c_job="Content"
              c_desc="Magni qui quod omnis unde et eos fuga et exercitationem. Odio veritatis perspiciatis quaerat qui aut aut aut"
            />
          </div>
        </section>
        <Footer />
      </main>
    </div>
  )
}
